jpackage `
    --type exe `
    --name PasswordManager `
    --input .\compiled `
    --dest .\compiled `
    --main-jar PasswordManager.jar `
    --main-class Main `
    --app-version 2.2.1 `
    --description "Password Manager is an application able to add, modify and delete locally saved accounts, characterized by a software, a username and an AES-encrypted password." `
    --copyright "Copyright (C) 2022-2023  Francesco Marras  GNU GPLv3" `
    --license-file .\license.txt `
    --icon .\locker.ico `
    --about-url "https://github.com/Achille004/PasswordManager"